export const PLANS = [
  {
    id: 'launch',
    name: 'LAUNCH',
    price: 297,
    billing: 'month',
    description: 'Perfect for getting started with JD Productions services',
    features: [
      'Custom Website',
      'Stripe Integration',
      'Mobile Optimized',
      '72-Hour Turnaround',
      'Email Support',
    ],
    stripeProductId: 'prod_launch',
    stripePriceId: 'price_launch_monthly',
    featured: false,
  },
  {
    id: 'grow',
    name: 'GROW',
    price: 997,
    billing: 'month',
    description: 'Advanced services for scaling your business systems',
    features: [
      'Everything in LAUNCH',
      'Systems Design',
      'Workflow Automation',
      'AI Integration',
      'Advanced Analytics',
      'Priority Support',
      'Monthly Strategy Review',
    ],
    stripeProductId: 'prod_grow',
    stripePriceId: 'price_grow_monthly',
    featured: true,
  },
  {
    id: 'scale',
    name: 'SCALE',
    price: 5000,
    billing: 'month',
    description: 'Enterprise-grade systems architecture and operations',
    features: [
      'Everything in GROW',
      'Dedicated Account Manager',
      'Custom Architecture Design',
      'Infrastructure Setup',
      'Team Training',
      'Quarterly Business Reviews',
      '24/7 Priority Support',
      'Custom Integrations',
    ],
    stripeProductId: 'prod_scale',
    stripePriceId: 'price_scale_monthly',
    featured: false,
  },
];

export const STRIPE_CONFIG = {
  publishableKey: process.env.VITE_STRIPE_PUBLISHABLE_KEY || 'pk_test_default',
  successUrl: process.env.VITE_STRIPE_SUCCESS_URL || 'https://accounts.jdproductions.io/dashboard',
  cancelUrl: process.env.VITE_STRIPE_CANCEL_URL || 'https://accounts.jdproductions.io/pricing',
};
